### ISSUE TITLE
yajl not found error

### ISSUE THREAD

**Issue by vipuljain123** [AMDmi3/jsonslicer#45]
Hi,
Even after successfully installed yajl-0.3.5, I am getting following error while installing jsonslicer.

vipul@localhost:/opt/installer$ pip3 install jsonslicer 
Collecting jsonslicer
  Using cached https://files.pythonhosted.org/packages/61/ec/75c764f881625c97d2d9e9e06fe1b9aa6d145dee8b327d73cd76b36aeec2/jsonslicer-0.1.5.tar.gz
    Complete output from command python setup.py egg_info:
    Package yajl was not found in the pkg-config search path.
    Perhaps you should add the directory containing `yajl.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'yajl' found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-5aac89jn/jsonslicer/setup.py", line 87, in <module>
        **pkgconfig('yajl')
      File "/tmp/pip-build-5aac89jn/jsonslicer/setup.py", line 16, in pkgconfig
        for token in subprocess.check_output(['pkg-config', '--libs', '--cflags', package]).decode('utf-8').split():
      File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
        **kwargs).stdout
      File "/usr/lib/python3.6/subprocess.py", line 438, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['pkg-config', '--libs', '--cflags', 'yajl']' returned non-zero exit status 1.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-5aac89jn/jsonslicer/
vipul@localhost:/opt/installer$

**Comment by AMDmi3** [comment]
It says clearly that pkg-config cannot find yajl, please check your yajl installation.

**Comment by vipuljain123** [comment]
![Screenshot from 2020-05-20 20-17-31](https://user-images.githubusercontent.com/50237381/82460680-19387d00-9ad7-11ea-9a81-193000b29e10.png)

**Comment by AMDmi3** [comment]
You need [yajl library](https://lloyd.github.io/yajl/), not yajl python module.

**Comment by vipuljain123** [comment]
Thanks @AMDmi3 . Issued resolved now.
