### ISSUE TITLE
installation instructions are lacking

### ISSUE THREAD

**Issue by MatthewK100000** [AMDmi3/jsonslicer#46]
Hello, 

I want to install this package but I'm getting the following error:

`ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.6/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/c2/cnf131qj7tb0slpsnj_v8h_h0000gp/T/pip-install-70kc1_kr/jsonslicer/setup.py'"'"'; __file__='"'"'/private/var/folders/c2/cnf131qj7tb0slpsnj_v8h_h0000gp/T/pip-install-70kc1_kr/jsonslicer/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/c2/cnf131qj7tb0slpsnj_v8h_h0000gp/T/pip-pip-egg-info-9eh5xu2r
         cwd: /private/var/folders/c2/cnf131qj7tb0slpsnj_v8h_h0000gp/T/pip-install-70kc1_kr/jsonslicer/
    Complete output (15 lines):
    Package yajl was not found in the pkg-config search path.
    Perhaps you should add the directory containing `yajl.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'yajl' found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/c2/cnf131qj7tb0slpsnj_v8h_h0000gp/T/pip-install-70kc1_kr/jsonslicer/setup.py", line 87, in <module>
        **pkgconfig('yajl')
      File "/private/var/folders/c2/cnf131qj7tb0slpsnj_v8h_h0000gp/T/pip-install-70kc1_kr/jsonslicer/setup.py", line 16, in pkgconfig
        for token in subprocess.check_output(['pkg-config', '--libs', '--cflags', package]).decode('utf-8').split():
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 336, in check_output
        **kwargs).stdout
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 418, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['pkg-config', '--libs', '--cflags', 'yajl']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`
I've installed `pkg-config` via homebrew: `brew install pkg-config`. And I've downloaded the version 2.1.0 yajl installation folder from http://lloyd.github.io/yajl/ and renamed it to "yajl." Then I put this folder within my site-packages folder. I can't get this library to work. 

Please help. Thanks!

**Comment by AMDmi3** [comment]
You need to compile and install `libyajl`, not copy it to site-packages. It's available from homebrew as well.
