### ISSUE TITLE
Question how to read Element that is a tuple. 

### ISSUE THREAD

**Issue by ChrisChross** [AMDmi3/jsonslicer#50]
Hey guys, 

thanks for creating this json stream slicer. I am currently looking for a way how to read a json file in this formt:
```
{
    "Elem1": [
       {
            "orgs": [],
       },
       {
           "people":[]
       },
    ],
   "Elem2"":[
       {
            "orgs": [],
       },
       {
           "people":[]
       },
    ],
...
}
```
However, I struggle with the tuple format the second argument (`path_prefix: Tuple[Union[str, bytes, None], ...]`) takes.
Is there a way how I could read the file above element-wise i.e. Elem1, Elem2, ... . Each element is saved as a tuple with two dicts in it. If I just do `for ehem in JsonSlicer(data, (None, None)` I only get one dict at a time. What I'd like two have is both at the same read time. Any ideas how to do that? Would appreciate your help! 

Best regards 
Chris

**Comment by AMDmi3** [comment]
If I understand correctly, you need `JsonSlicer(data, (None,))` which would give you `[{'orgs': []}, {'people': []}]`, then the second `[{'orgs': []}, {'people': []}]` etc.

The second argument is a mask for a path within json with `None` acting as a placeholder. For instance, `()` just picks the topmost element (which is not very useful), `(None,)` iterates over all childs of the topmost element, `(None, None)` iterates over the elements at the second nesting level, `("Elem1", None)` iterates over childs of Elem1 etc. In terms of filesystem paths equivalents for these would be `/`, `/*`, `/*/*`, `/Elem1/*`

**Comment by ChrisChross** [comment]
Thank you! That helps me a lot.
