### ISSUE TITLE
3.9 support or something else?

### ISSUE THREAD

**Issue by kornicameister** [AMDmi3/jsonslicer#52]
Hey,

I am trying to run `jsonslicer` under `3.9.x`: 

```bash
$ python --version  
Python 3.9.1
```

but there's an error:

```bash
python -c 'from jsonslicer import JsonSlicer' 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: /home/trebskit/.pyenv/versions/fdas_integration_aq/lib/python3.9/site-packages/jsonslicer.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZSt7nothrow
```

any ideas or hints?

**Comment by AMDmi3** [comment]
I use 3.9 myself, no problems. How did you install jsonslicer, can you please post a build log?

PS. setuptools is known to be broken and use C compiler when building C++ extensions, may try specifying correct compiler for build:

```shell
CC=c++ python3 setup.py build
```

**Comment by kornicameister** [comment]
I ran `pip install`. I can try and see if another compiler approach works

**Comment by frafra** [comment]
No problem here on Fedora 34 x86_64 with Python 3.9.5.
