### ISSUE TITLE
Parsing error shows no JSON snippet

### ISSUE THREAD

**Issue by frafra** [AMDmi3/jsonslicer#53]
Hi,
this is the end of my traceback:
```
    for feature in JsonSlicer(req.raw, ('features', None)):
RuntimeError: YAJL error: lexical error: invalid char in json text.
                                                            (right here) ------^
```
YAJL is pointing out at a specific portion in the JSON file, but I do not see it in the output.

**Comment by AMDmi3** [comment]
JsonSlicer passes error text got from [yajl_get_error](https://lloyd.github.io/yajl/yajl-1.0.12/yajl__parse_8h.html#aa4f26259fea6bb058b17828598532198) call as is, so it's exactly as yajl reports it. It may be that it really has no visible characters for context as demonstrated by:

```python
from jsonslicer import JsonSlicer
import io

try:
    for feature in JsonSlicer(io.BytesIO(b''), (None,)):
        pass
except Exception as e:
    print(e)
```

So I can't change the error, however it looks like it would make sense to make `verbose` argument tunable.
