### ISSUE TITLE
Question: Output as Bytes instead of Python Object

### ISSUE THREAD

**Issue by pahansen95** [AMDmi3/jsonslicer#54]
I have a use case where I read multiple JSON messages from a stream (ex. stdin) & then forward each individual message using MQTT.

I'm using jsonslicer to parse the input stream but is there a way I can have the `JsonSlicer` instance yield the message as a bytes object before it converts it to a Python object? 

### Example

```python
# ...

json_msgs = jsonslicer.JsonSlicer(
    input_stream,
    (), # Matches the entire JSON Object
    yajl_allow_multiple_values=True,
    yajl_allow_trailing_garbage=True,
  )

# What I want
msg: bytes = next(json_msgs)

# What I'm doing
msg: bytes = json.dumps(
  next(json_msgs)
).encode()

mqtt_client.publish(msg, "TOPIC")

# ...
```

**Comment by AMDmi3** [comment]
No. The python object hierarchy is constructed on the fly by jsonslicer, there's no bytes object in the process.
