### ISSUE TITLE
Documentation suggestion Debian (docker) install

### ISSUE THREAD

**Issue by nymann** [AMDmi3/jsonslicer#55]
Hey AMDmi3,

Thanks for a great piece of software.

I was wondering if it would bring any value, to add some documentation (wiki entry) about installation in a Debian based Docker setup?

It seems like there's a lot of closed issues through the years regarding installation issues.

## Debian
The following is the build and runtime requirements for Debian (bookworm)

### Build time
- gcc
- g++
- pkg-config
- libyajl-dev
- python3-dev

### Runtime
- libyajl2
-  python3

### Docker Example
To showcase the above, I made the following `Dockerfile`.

```Dockerfile
ARG DEBIAN_VERSION=bookworm

FROM debian:$DEBIAN_VERSION as base-img
ENV VENV="$HOME/.venv"
ENV PATH="$VENV/bin:$PATH"

RUN apt-get update && \
    apt-get install --assume-yes --no-install-recommends \
        libyajl2 \
        python3 && \
    rm -rf /var/lib/apt/lists/*

FROM base-img as compile-img
RUN apt-get update && \
    apt-get install --assume-yes --no-install-recommends \
        python3-dev \
        gcc \
        g++ \
        pkg-config \
        python3-pip \
        python3-venv \
        libyajl-dev && \
    rm -rf /var/lib/apt/lists/*
RUN python3 -m venv $VENV && \
    pip install --upgrade pip jsonslicer

FROM base-img as production-img
COPY --from=compile-img "$VENV" "$VENV"
CMD python3 -c "import jsonslicer;print('Hello from JsonSlicer')"
```
```sh
$ docker build -f Dockerfile -t jsonslicer-test .
$ docker run -it jsonslicer-test
Hello from JsonSlicer
```

**Comment by AMDmi3** [comment]
Sorry, I don't see any value in highly specialized instructions for one specific environment, especially I cannot maintain myself. Jsonslicer build process is straightforward and the same for all platforms, and dependencies are listed in the readme.

**Comment by nymann** [comment]
> Sorry, I don't see any value in highly specialized instructions for one specific environment, especially I cannot maintain myself. Jsonslicer build process is straightforward and the same for all platforms, and dependencies are listed in the readme.

I guess my point is that all the requirements are not listed in the readme. Since Python3 and libyajl2 is not enough to `pip install jsonslicer`.
