### ISSUE TITLE
Wheel not available

### ISSUE THREAD

**Issue by HarryWeppner** [AMDmi3/jsonslicer#56]
Hi @AMDmi3, Thanks for the great work!

Have you explored packaging this as a wheel (or conda package)? If not, are you open to a contribution in this area?

**Comment by AMDmi3** [comment]
I do not and will not distribute any binaries

**Comment by HarryWeppner** [comment]
Ok. Out of curiosity, is that because you anticipate a potentially high maintenance effort over time?

**Comment by AMDmi3** [comment]
That's because there's no reason to distribute F/OSS as blobs.

**Comment by HarryWeppner** [comment]
The difficulty is that you have to rely on a tool chain to install the package at runtime. In a production context, that's problematic.

Appreciate your quick response nevertheless.

**Comment by AMDmi3** [comment]
Normally you would build distro-native package (or your distro should already have one) or a complete container to deploy to production. You don't need wheels and of course you should never build at runtime.
